/**
  @file
  @brief Datalines for BE_LOG_EVENTO dataset
  @details Generated by %mp_ds2cards()
    Source: https://github.com/sasjs/core
  @cond 
**/
data work.MONITOR_LOG_EVENTO ;
attrib 
LOG_UID                          length= 8      format=9. label="LOG_UID"
LOG_EVENTO                       length= $200   format=$200. label="LOG_EVENTO"
LOG_DATETIME                     length= 8      format=DATETIME27.6 label="LOG_DATETIME"
LOG_USUARIO                      length= $30    format=$30. label="LOG_USUARIO"
LOG_TIPO_EVENTO                  length= $16    format=$16. label="LOG_TIPO_EVENTO"
LOG_ROLE                         length= $30    format=$30. label="LOG_ROLE"


LOG_UID
LOG_EVENTO
LOG_DATETIME
LOG_USUARIO
LOG_TIPO_EVENTO

;
infile cards dsd;
input 
  LOG_UID
  GRP_CODIGO                       :$char.
  LOG_EVENTO                       :$char.
  LOG_DATETIME
  LOG_USUARIO                      :$char.
  LOG_TIPO_EVENTO                  :$char.
;
missing a b c d e f g h i j k l m n o p q r s t u v w x y z _;
datalines4;
1,log,2007201485,gschade,002,SASADM
;;;;
run;
/** @endcond **/
